version: "3.1"

services:
  db:
    image: ghcr.io/modhanami/arsahub/database
    environment:
      POSTGRES_DB: arsahub
      POSTGRES_PASSWORD: 123456
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
  #    ports:
  #      - "5433:5432"

  backend:
    image: ghcr.io/modhanami/arsahub/backend
    environment:
      DB_URL: jdbc:postgresql://db:5432/arsahub
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    env_file:
      - .env
  #    ports:
  #      - "8080:8080"
  #      - "9097:9097"

  frontend:
    image: ghcr.io/modhanami/arsahub/frontend
  #    ports:
  #      - "3000:3000"

  reverse-proxy:
    image: ghcr.io/modhanami/arsahub/reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/ssl:/etc/nginx/ssl

volumes:
  db-data:
