version: "3.1"

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d

  backend:
    image: modhanami/arsahub-backend:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "9097:9097"

  frontend:
    build: ./frontend
    image: modhanami/arsahub-frontend-local:latest
    ports:
      - "3000:3000"

  reverse-proxy:
    build: ./reverse-proxy
    image: modhanami/arsahub-reverse-proxy:latest
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
