version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: arsahub

  backend:
    image: modhanami/arsahub-backend-dev:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/arsahub?user=postgres&password=123456
    ports:
      - "9000:8080"