# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./dump/${DB_DUMP_FILE}:/docker-entrypoint-initdb.d/${DB_DUMP_FILE}
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: arsahub
