-- liquibase formatted sql

-- changeset Rooted:1695459676198-1
CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

-- changeset Rooted:1695459676198-2
CREATE TABLE user_events
(
    event_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    CONSTRAINT pk_user_events PRIMARY KEY (event_id, user_id)
);

-- changeset Rooted:1695459676198-3
ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

-- changeset Rooted:1695459676198-4
ALTER TABLE user_events
    ADD CONSTRAINT fk_useeve_on_event FOREIGN KEY (event_id) REFERENCES event (event_id);

-- changeset Rooted:1695459676198-5
ALTER TABLE user_events
    ADD CONSTRAINT fk_useeve_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);
