-- liquibase formatted sql

-- changeset Rooted:1695443436540-1
CREATE TABLE event
(
    event_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255),
    location     VARCHAR(255),
    start_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    organizer_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (event_id)
);

-- changeset Rooted:1695443436540-2
CREATE TABLE organizer
(
    organizer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_organizer PRIMARY KEY (organizer_id)
);

-- changeset Rooted:1695443436540-3
ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES organizer (organizer_id);
