-- liquibase formatted sql

-- changeset Rooted:1700671243801-1
CREATE TABLE achievement
(
    achievement_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          TEXT   NOT NULL,
    description    TEXT,
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    image_url      TEXT,
    activity_id    BIGINT NOT NULL,
    CONSTRAINT idx_16391_primary PRIMARY KEY (achievement_id)
);

-- changeset Rooted:1700671243801-2
CREATE TABLE action
(
    effect_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       TEXT NOT NULL,
    description TEXT,
    json_schema JSONB,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    key TEXT NOT NULL,
    CONSTRAINT idx_16416_primary PRIMARY KEY (effect_id)
);

-- changeset Rooted:1700671243801-3
CREATE TABLE activity
(
    activity_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              TEXT NOT NULL,
    description        TEXT,
    created_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    external_system_id BIGINT,
    CONSTRAINT idx_16407_primary PRIMARY KEY (activity_id)
);

-- changeset Rooted:1700671243801-4
CREATE TABLE custom_unit
(
    unit_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       TEXT NOT NULL,
    key TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT unit_pkey PRIMARY KEY (unit_id)
);

-- changeset Rooted:1700671243801-5
CREATE TABLE external_system
(
    external_system_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              TEXT NOT NULL,
    description        TEXT,
    api_key UUID NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT idx_16500_primary PRIMARY KEY (external_system_id)
);

-- changeset Rooted:1700671243801-6
CREATE TABLE rule
(
    rule_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           TEXT   NOT NULL,
    description     TEXT,
    activity_id     BIGINT NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    trigger_id      BIGINT NOT NULL,
    trigger_type_id BIGINT,
    effect_id       BIGINT NOT NULL,
    trigger_type_params JSONB,
    effect_params JSONB,
    trigger_params JSONB,
    CONSTRAINT idx_16438_primary PRIMARY KEY (rule_id)
);

-- changeset Rooted:1700671243801-7
CREATE TABLE rule_progress_streak
(
    rule_progress_streak_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rule_id                 BIGINT  NOT NULL,
    user_activity_id        BIGINT  NOT NULL,
    current_streak          INTEGER NOT NULL,
    last_interaction_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT idx_16456_primary PRIMARY KEY (rule_progress_streak_id)
);

-- changeset Rooted:1700671243801-8
CREATE TABLE rule_progress_times
(
    rule_progress_single_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rule_id                 BIGINT  NOT NULL,
    user_activity_id        BIGINT  NOT NULL,
    progress                INTEGER NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at              TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    completed_at            TIMESTAMP WITH TIME ZONE,
    CONSTRAINT idx_16462_primary PRIMARY KEY (rule_progress_single_id)
);

-- changeset Rooted:1700671243801-9
CREATE TABLE trigger
(
    trigger_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       TEXT NOT NULL,
    description TEXT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    key TEXT NOT NULL,
    json_schema JSONB,
    CONSTRAINT idx_16468_primary PRIMARY KEY (trigger_id)
);

-- changeset Rooted:1700671243801-10
CREATE TABLE trigger_type
(
    trigger_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           TEXT NOT NULL,
    description     TEXT,
    json_schema JSONB,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    key TEXT NOT NULL,
    CONSTRAINT idx_16483_primary PRIMARY KEY (trigger_type_id)
);

-- changeset Rooted:1700671243801-11
CREATE TABLE "user"
(
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username           TEXT NOT NULL,
    name               TEXT NOT NULL,
    external_user_id   TEXT NOT NULL,
    external_system_id BIGINT,
    created_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT idx_16492_primary PRIMARY KEY (user_id)
);

-- changeset Rooted:1700671243801-12
CREATE TABLE user_activity
(
    user_activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT  NOT NULL,
    activity_id      BIGINT  NOT NULL,
    points           INTEGER NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT idx_16425_primary PRIMARY KEY (user_activity_id)
);

-- changeset Rooted:1700671243801-13
CREATE TABLE user_activity_achievement
(
    user_activity_achievement_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    achievement_id               BIGINT NOT NULL,
    user_activity_id             BIGINT NOT NULL,
    completed_at                 TIMESTAMP WITH TIME ZONE,
    created_at                   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at                   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT idx_16400_primary PRIMARY KEY (user_activity_achievement_id)
);

-- changeset Rooted:1700671243801-14
CREATE TABLE user_activity_point_history
(
    user_activity_point_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_activity_id               BIGINT  NOT NULL,
    activity_id                    BIGINT  NOT NULL,
    points                         INTEGER NOT NULL,
    created_at                     TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    description                    TEXT,
    CONSTRAINT idx_16432_primary PRIMARY KEY (user_activity_point_history_id)
);

-- changeset Rooted:1700671243801-15
CREATE TABLE user_activity_progress
(
    user_activity_progress_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    activity_id               BIGINT  NOT NULL,
    user_activity_id          INTEGER NOT NULL,
    unit_id                   INTEGER NOT NULL,
    progress_value            INTEGER NOT NULL,
    created_at                TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at                TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT user_activity_progress_pkey PRIMARY KEY (user_activity_progress_id)
);

-- changeset Rooted:1700671243801-16
ALTER TABLE action
    ADD CONSTRAINT action_un UNIQUE (key);

-- changeset Rooted:1700671243801-17
CREATE INDEX idx_16438_activity_id ON rule (activity_id);

-- changeset Rooted:1700671243801-18
CREATE INDEX idx_16438_effect_id ON rule (effect_id);

-- changeset Rooted:1700671243801-19
CREATE INDEX idx_16438_trigger_id ON rule (trigger_id);

-- changeset Rooted:1700671243801-20
CREATE INDEX idx_16438_trigger_type_id ON rule (trigger_type_id);

-- changeset Rooted:1700671243801-21
CREATE INDEX idx_16456_rule_id ON rule_progress_streak (rule_id);

-- changeset Rooted:1700671243801-22
CREATE INDEX idx_16456_user_activity_id ON rule_progress_streak (user_activity_id);

-- changeset Rooted:1700671243801-23
CREATE INDEX idx_16462_rule_id ON rule_progress_times (rule_id);

-- changeset Rooted:1700671243801-24
CREATE INDEX idx_16462_user_activity_id ON rule_progress_times (user_activity_id);

-- changeset Rooted:1700671243801-25
ALTER TABLE trigger
    ADD CONSTRAINT trigger_un UNIQUE (key);

-- changeset Rooted:1700671243801-26
ALTER TABLE trigger_type
    ADD CONSTRAINT trigger_type_un UNIQUE (key);

-- changeset Rooted:1700671243801-27
CREATE UNIQUE INDEX idx_16492_external_user_id ON "user" (external_user_id);

-- changeset Rooted:1700671243801-28
CREATE INDEX idx_16425_activity_id ON user_activity (activity_id);

-- changeset Rooted:1700671243801-29
CREATE INDEX idx_16425_user_id ON user_activity (user_id);

-- changeset Rooted:1700671243801-30
CREATE INDEX idx_16400_achievement_id ON user_activity_achievement (achievement_id);

-- changeset Rooted:1700671243801-31
CREATE INDEX idx_16432_activity_id ON user_activity_point_history (activity_id);

-- changeset Rooted:1700671243801-32
CREATE INDEX idx_16432_user_activity_id ON user_activity_point_history (user_activity_id);

-- changeset Rooted:1700671243801-33
CREATE
SEQUENCE  IF NOT EXISTS achievement_activity_id_seq AS bigint START
WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE
1;

-- changeset Rooted:1700671243801-34
ALTER TABLE achievement
    ADD CONSTRAINT achievement_fk FOREIGN KEY (activity_id) REFERENCES activity (activity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-35
ALTER TABLE activity
    ADD CONSTRAINT activity_fk FOREIGN KEY (external_system_id) REFERENCES external_system (external_system_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-36
ALTER TABLE rule
    ADD CONSTRAINT rule_ibfk_1 FOREIGN KEY (activity_id) REFERENCES activity (activity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-37
ALTER TABLE rule
    ADD CONSTRAINT rule_ibfk_2 FOREIGN KEY (trigger_id) REFERENCES trigger (trigger_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-38
ALTER TABLE rule
    ADD CONSTRAINT rule_ibfk_3 FOREIGN KEY (trigger_type_id) REFERENCES trigger_type (trigger_type_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-39
ALTER TABLE rule
    ADD CONSTRAINT rule_ibfk_4 FOREIGN KEY (effect_id) REFERENCES action (effect_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-40
ALTER TABLE rule_progress_streak
    ADD CONSTRAINT rule_progress_streak_ibfk_1 FOREIGN KEY (rule_id) REFERENCES rule (rule_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-41
ALTER TABLE rule_progress_streak
    ADD CONSTRAINT rule_progress_streak_ibfk_2 FOREIGN KEY (user_activity_id) REFERENCES user_activity (user_activity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-42
ALTER TABLE rule_progress_times
    ADD CONSTRAINT rule_progress_times_ibfk_1 FOREIGN KEY (rule_id) REFERENCES rule (rule_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-43
ALTER TABLE rule_progress_times
    ADD CONSTRAINT rule_progress_times_ibfk_2 FOREIGN KEY (user_activity_id) REFERENCES user_activity (user_activity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-44
ALTER TABLE user_activity_achievement
    ADD CONSTRAINT user_activity_achievement_ibfk_1 FOREIGN KEY (achievement_id) REFERENCES achievement (achievement_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-45
ALTER TABLE user_activity_achievement
    ADD CONSTRAINT user_activity_achievement_ibfk_2 FOREIGN KEY (user_activity_id) REFERENCES user_activity (user_activity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-46
ALTER TABLE user_activity
    ADD CONSTRAINT user_activity_ibfk_1 FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-47
ALTER TABLE user_activity
    ADD CONSTRAINT user_activity_ibfk_2 FOREIGN KEY (activity_id) REFERENCES activity (activity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-48
ALTER TABLE user_activity_point_history
    ADD CONSTRAINT user_activity_point_history_ibfk_1 FOREIGN KEY (user_activity_id) REFERENCES user_activity (user_activity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-49
ALTER TABLE user_activity_point_history
    ADD CONSTRAINT user_activity_point_history_ibfk_2 FOREIGN KEY (activity_id) REFERENCES activity (activity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-50
ALTER TABLE user_activity_progress
    ADD CONSTRAINT user_activity_progress_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES activity (activity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-51
ALTER TABLE user_activity_progress
    ADD CONSTRAINT user_activity_progress_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES custom_unit (unit_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-52
ALTER TABLE user_activity_progress
    ADD CONSTRAINT user_activity_progress_user_activity_id_fkey FOREIGN KEY (user_activity_id) REFERENCES user_activity (user_activity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1700671243801-53
ALTER TABLE "user"
    ADD CONSTRAINT user_ibfk_1 FOREIGN KEY (external_system_id) REFERENCES external_system (external_system_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

