-- liquibase formatted sql

-- changeset Rooted:1701002508891-1
CREATE TABLE rule_template
(
    rule_template_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                TEXT    NOT NULL,
    description         TEXT,
    trigger_template_id BIGINT  NOT NULL,
    action_id           BIGINT  NOT NULL,
    external_system_id  INTEGER NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    effect_params JSONB,
    trigger_params JSONB,
    CONSTRAINT rule_template_pk PRIMARY KEY (rule_template_id)
);

-- changeset Rooted:1701002508891-2
CREATE TABLE trigger_template
(
    title                   TEXT   NOT NULL,
    description             TEXT,
    key TEXT NOT NULL,
    json_schema JSONB,
    integration_template_id BIGINT NOT NULL,
    trigger_template_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT trigger_template_pk PRIMARY KEY (trigger_template_id)
);

-- changeset Rooted:1701002508891-3
CREATE TABLE integration_template
(
    name                    TEXT   NOT NULL,
    description             TEXT,
    integration_id          BIGINT NOT NULL,
    integration_template_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT integration_template_pk PRIMARY KEY (integration_template_id)
);

-- changeset Rooted:1701002508891-4
ALTER TABLE trigger
    ADD integration_id BIGINT NOT NULL;

-- changeset Rooted:1701002508891-5
ALTER TABLE integration_template
    ADD CONSTRAINT integration_template_external_system_external_system_id_fk FOREIGN KEY (integration_id) REFERENCES external_system (external_system_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1701002508891-6
ALTER TABLE rule_template
    ADD CONSTRAINT rule_template_action_effect_id_fk FOREIGN KEY (action_id) REFERENCES action (effect_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1701002508891-7
ALTER TABLE rule_template
    ADD CONSTRAINT rule_template_external_system_external_system_id_fk FOREIGN KEY (external_system_id) REFERENCES external_system (external_system_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1701002508891-8
ALTER TABLE rule_template
    ADD CONSTRAINT rule_template_trigger_trigger_id_fk FOREIGN KEY (trigger_template_id) REFERENCES trigger_template (trigger_template_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1701002508891-9
ALTER TABLE trigger
    ADD CONSTRAINT trigger_external_system_external_system_id_fk FOREIGN KEY (integration_id) REFERENCES external_system (external_system_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Rooted:1701002508891-10
ALTER TABLE trigger_template
    ADD CONSTRAINT trigger_template_external_system_external_system_id_fk FOREIGN KEY (integration_template_id) REFERENCES integration_template (integration_template_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

