create sequence achievement_activity_id_seq;

create sequence rule_progress_times_rule_progress_single_id_seq;

create sequence user_activity_progress_user_activity_progress_id_seq;

create sequence rule_type_rule_type_id_seq;

create table "user"
(
    user_id    bigint generated by default as identity
        constraint idx_16492_primary
        primary key,
    username   text                                               not null,
    name       text                                               not null,
    created_at timestamp with time zone default now()             not null,
    updated_at timestamp with time zone default now()             not null,
    uuid       uuid                     default gen_random_uuid() not null
);

create table app
(
    app_id      bigint generated by default as identity
        constraint idx_16500_primary
        primary key,
    title       text                                   not null,
    description text,
    api_key     text                                   not null,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    owner_id    bigint                                 not null
        constraint app_user_user_id_fk
        references "user"
);

create table achievement
(
    achievement_id bigint generated by default as identity
        constraint idx_16391_primary
        primary key,
    title          text                                   not null,
    description    text,
    created_at     timestamp with time zone default now() not null,
    updated_at     timestamp with time zone default now() not null,
    image_url      text,
    app_id         bigint
        constraint achievement_app_app_id_fk
        references app
);

create table trigger
(
    trigger_id  bigint generated by default as identity
        constraint idx_16468_primary
        primary key,
    title       text                                   not null,
    description text,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    key         text                                   not null,
    json_schema jsonb,
    app_id      bigint                                 not null
        constraint trigger_app_app_id_fk
        references app
);

create table rule
(
    rule_id               bigint generated by default as identity
        constraint idx_16438_primary
        primary key,
    title                 text   not null,
    description           text,
    created_at            timestamp with time zone default now() not null,
    updated_at            timestamp with time zone default now() not null,
    trigger_id            bigint not null
        constraint rule_ibfk_2
        references trigger,
    trigger_params jsonb,
    app_id                bigint
        constraint rule_app_app_id_fk
        references app,
    conditions jsonb,
    action                text   not null,
    action_points         integer,
    action_achievement_id bigint
        constraint rule_achievement_achievement_id_fk
        references achievement,
    repeatability         text   not null
);

create index idx_16438_trigger_id
    on rule (trigger_id);

create table app_user
(
    app_user_id  bigint generated by default as identity
        primary key,
    unique_id    text                                not null,
    display_name text                                not null,
    created_at   timestamp default CURRENT_TIMESTAMP not null,
    updated_at   timestamp default CURRENT_TIMESTAMP,
    app_id       bigint                              not null
        constraint app_user_app_app_id_fk
        references app,
    points       integer   default 0                 not null
);

create table rule_progress
(
    rule_progress_id bigint generated by default as identity
        constraint idx_16462_primary
        primary key,
    rule_id          bigint not null
        constraint rule_progress_times_ibfk_1
        references rule,
    activation_count integer,
    created_at       timestamp with time zone default now() not null,
    updated_at       timestamp with time zone default now() not null,
    completed_at     timestamp with time zone,
    app_user_id      bigint
        constraint rule_progress_app_user_app_user_id_fk
        references app_user
);

alter
sequence rule_progress_times_rule_progress_single_id_seq owned by rule_progress.rule_progress_id;

create index idx_16462_rule_id
    on rule_progress (rule_id);

create table custom_unit_type
(
    custom_unit_type_id bigserial
        constraint custom_unit_type_pk
        primary key,
    name                text not null
);

create table custom_unit
(
    unit_id             bigint generated by default as identity
        constraint unit_pkey
        primary key,
    name                text                                   not null,
    key                 text                                   not null,
    created_at          timestamp with time zone default now() not null,
    updated_at          timestamp with time zone default now() not null,
    app_id              bigint                                 not null
        constraint custom_unit___fk
        references app,
    custom_unit_type_id integer                                not null
        constraint custom_unit_custom_unit_type_custom_unit_type_id_fk
        references custom_unit_type
);

create table app_user_progress
(
    app_user_activity_progress_id bigint generated by default as identity
        constraint user_activity_progress_pkey
        primary key,
    unit_id                       integer                 not null
        constraint user_activity_progress_unit_id_fkey
        references custom_unit,
    created_at                    timestamp default now() not null,
    updated_at                    timestamp default now() not null,
    value_int                     integer,
    value_int_array               integer[],
    app_user_id                   bigint
        constraint app_user_progress_app_user_app_user_id_fk
        references app_user
);

alter sequence user_activity_progress_user_activity_progress_id_seq owned by app_user_progress.app_user_activity_progress_id;

create table rule_activation_type
(
    rule_activation_type_id bigint default nextval('rule_type_rule_type_id_seq'::regclass) not null
        constraint rule_type_pk
        primary key,
    name                    text                                                           not null
);

alter sequence rule_type_rule_type_id_seq owned by rule_activation_type.rule_activation_type_id;

create table trigger_log
(
    trigger_log_id bigserial
        constraint trigger_log_pk
        primary key,
    trigger_id     integer
        constraint trigger_log_trigger_trigger_id_fk
        references trigger,
    request_body   jsonb  not null,
    app_id         bigint not null
        constraint trigger_log_app_app_id_fk
        references app,
    app_user_id    bigint not null
        constraint trigger_log_app_user_app_user_id_fk
        references app_user
);

create table app_user_achievement
(
    app_user_achievement_id bigint generated by default as identity
        constraint pk_app_user_achievement
        primary key,
    achievement_id          bigint not null
        constraint fk_app_user_achievement_on_achievement
        references achievement,
    app_user_id             bigint not null
        constraint fk_app_user_achievement_on_app_user
        references app_user,
    completed_at            timestamp
);

