create sequence achievement_activity_id_seq;

create sequence trigger_template_app_tempalte_id_seq;

create table if not exists action
(
    action_id   bigint generated by default as identity
        constraint idx_16416_primary
        primary key,
    title       text                                   not null,
    description text,
    json_schema jsonb,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    key         text                                   not null
        constraint action_un
        unique
);

create table if not exists custom_unit
(
    unit_id    bigint generated by default as identity
        constraint unit_pkey
        primary key,
    name       text                                   not null,
    key        text                                   not null,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null
);

create table if not exists trigger_type
(
    trigger_type_id bigint generated by default as identity
        constraint idx_16483_primary
        primary key,
    title           text                                   not null,
    description     text,
    json_schema     jsonb,
    created_at      timestamp with time zone default now() not null,
    updated_at      timestamp with time zone default now() not null,
    key             text                                   not null
        constraint trigger_type_un
        unique
);

create table if not exists "user"
(
    user_id    bigint generated by default as identity
        constraint idx_16492_primary
        primary key,
    username   text                                   not null,
    name       text                                   not null,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null
);

create table if not exists app
(
    app_id      bigint generated by default as identity
        constraint idx_16500_primary
        primary key,
    title       text                                   not null,
    description text,
    api_key     uuid                                   not null,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    created_by  bigint                                 not null
        constraint app_user_user_id_fk
        references "user"
);

create table if not exists activity
(
    activity_id bigint generated by default as identity
        constraint idx_16407_primary
        primary key,
    title       text                                   not null,
    description text,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    app_id      bigint
        constraint activity_fk
        references app
);

create table if not exists achievement
(
    achievement_id bigint generated by default as identity
        constraint idx_16391_primary
        primary key,
    title          text                                   not null,
    description    text,
    created_at     timestamp with time zone default now() not null,
    updated_at     timestamp with time zone default now() not null,
    image_url      text,
    activity_id    bigint                                 not null
        constraint achievement_fk
        references activity
);

create table if not exists app_template
(
    name            text   not null,
    description     text,
    app_id          bigint not null
        constraint app_template_app_app_id_fk
        references app,
    app_template_id bigserial
        constraint app_template_pk
        primary key
);

create table if not exists trigger
(
    trigger_id  bigint generated by default as identity
        constraint idx_16468_primary
        primary key,
    title       text                                   not null,
    description text,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    key         text                                   not null,
    json_schema jsonb,
    app_id      bigint                                 not null
        constraint trigger_app_app_id_fk
        references app
);

create table if not exists rule
(
    rule_id             bigint generated by default as identity
        constraint idx_16438_primary
        primary key,
    title               text                                   not null,
    description         text,
    activity_id         bigint                                 not null
        constraint rule_ibfk_1
        references activity,
    created_at          timestamp with time zone default now() not null,
    updated_at          timestamp with time zone default now() not null,
    trigger_id          bigint                                 not null
        constraint rule_ibfk_2
        references trigger,
    trigger_type_id     bigint
        constraint rule_ibfk_3
        references trigger_type,
    action_id           bigint                                 not null
        constraint rule_ibfk_4
        references action,
    trigger_type_params jsonb,
    action_params       jsonb,
    trigger_params      jsonb
);

create index if not exists idx_16438_activity_id
    on rule (activity_id);

create index if not exists idx_16438_action_id
    on rule (action_id);

create index if not exists idx_16438_trigger_id
    on rule (trigger_id);

create index if not exists idx_16438_trigger_type_id
    on rule (trigger_type_id);

create table if not exists trigger_template
(
    title               text                                                                     not null,
    description         text,
    key                 text                                                                     not null,
    json_schema         jsonb,
    trigger_template_id bigint default nextval('trigger_template_app_tempalte_id_seq'::regclass) not null
        constraint trigger_template_pk
        primary key,
    app_template_id     bigint                                                                   not null
        constraint trigger_template_app_template_app_template_id_fk
        references app_template
);

alter sequence trigger_template_app_tempalte_id_seq owned by trigger_template.trigger_template_id;

create table if not exists rule_template
(
    rule_template_id    bigserial
        constraint rule_template_pk
        primary key,
    name                text                                   not null,
    description         text,
    trigger_template_id bigint                                 not null
        constraint rule_template_trigger_trigger_id_fk
        references trigger_template,
    action_id           bigint                                 not null
        constraint rule_template_action_action_id_fk
        references action,
    app_id              integer                                not null
        constraint rule_template_app_app_id_fk
        references app,
    created_at          timestamp with time zone default now() not null,
    updated_at          timestamp with time zone default now() not null,
    action_params       jsonb,
    trigger_params      jsonb
);

create table if not exists user_activity
(
    user_activity_id bigint generated by default as identity
        constraint idx_16425_primary
        primary key,
    user_id          bigint                                 not null
        constraint user_activity_ibfk_1
        references "user",
    activity_id      bigint                                 not null
        constraint user_activity_ibfk_2
        references activity,
    points           integer                                not null,
    created_at       timestamp with time zone default now() not null,
    updated_at       timestamp with time zone default now() not null
);

create table if not exists rule_progress_streak
(
    rule_progress_streak_id bigint generated by default as identity
        constraint idx_16456_primary
        primary key,
    rule_id                 bigint                                 not null
        constraint rule_progress_streak_ibfk_1
        references rule,
    user_activity_id        bigint                                 not null
        constraint rule_progress_streak_ibfk_2
        references user_activity,
    current_streak          integer                                not null,
    last_interaction_at     timestamp with time zone               not null,
    created_at              timestamp with time zone default now() not null
);

create index if not exists idx_16456_rule_id
    on rule_progress_streak (rule_id);

create index if not exists idx_16456_user_activity_id
    on rule_progress_streak (user_activity_id);

create table if not exists rule_progress_times
(
    rule_progress_single_id bigint generated by default as identity
        constraint idx_16462_primary
        primary key,
    rule_id                 bigint                                 not null
        constraint rule_progress_times_ibfk_1
        references rule,
    user_activity_id        bigint                                 not null
        constraint rule_progress_times_ibfk_2
        references user_activity,
    progress                integer                                not null,
    created_at              timestamp with time zone default now() not null,
    updated_at              timestamp with time zone default now() not null,
    completed_at            timestamp with time zone
);

create index if not exists idx_16462_rule_id
    on rule_progress_times (rule_id);

create index if not exists idx_16462_user_activity_id
    on rule_progress_times (user_activity_id);

create index if not exists idx_16425_activity_id
    on user_activity (activity_id);

create index if not exists idx_16425_user_id
    on user_activity (user_id);

create table if not exists user_activity_achievement
(
    user_activity_achievement_id bigint generated by default as identity
        constraint idx_16400_primary
        primary key,
    achievement_id               bigint                                 not null
        constraint user_activity_achievement_ibfk_1
        references achievement,
    user_activity_id             bigint                                 not null
        constraint user_activity_achievement_ibfk_2
        references user_activity,
    completed_at                 timestamp with time zone,
    created_at                   timestamp with time zone default now() not null,
    updated_at                   timestamp with time zone default now() not null
);

create index if not exists idx_16400_achievement_id
    on user_activity_achievement (achievement_id);

create table if not exists user_activity_point_history
(
    user_activity_point_history_id bigint generated by default as identity
        constraint idx_16432_primary
        primary key,
    user_activity_id               bigint                                 not null
        constraint user_activity_point_history_ibfk_1
        references user_activity,
    activity_id                    bigint                                 not null
        constraint user_activity_point_history_ibfk_2
        references activity,
    points                         integer                                not null,
    created_at                     timestamp with time zone default now() not null,
    description                    text
);

create index if not exists idx_16432_activity_id
    on user_activity_point_history (activity_id);

create index if not exists idx_16432_user_activity_id
    on user_activity_point_history (user_activity_id);

create table if not exists user_activity_progress
(
    user_activity_progress_id bigint generated by default as identity
        primary key,
    activity_id               bigint                  not null
        references activity,
    user_activity_id          integer                 not null
        references user_activity,
    unit_id                   integer                 not null
        references custom_unit,
    progress_value            integer                 not null,
    created_at                timestamp default now() not null,
    updated_at                timestamp default now() not null
);

