-- liquibase formatted sql

-- changeset Rooted:1695483434053-1
CREATE TABLE event
(
    event_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255) NOT NULL,
    description  VARCHAR(255),
    location     VARCHAR(255),
    start_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    organizer_id BIGINT       NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (event_id)
);

-- changeset Rooted:1695483434053-2
CREATE TABLE organizer
(
    organizer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255) NOT NULL,
    CONSTRAINT pk_organizer PRIMARY KEY (organizer_id)
);

-- changeset Rooted:1695483434053-3
CREATE TABLE "user"
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

-- changeset Rooted:1695483434053-4
CREATE TABLE user_events
(
    event_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    CONSTRAINT pk_user_events PRIMARY KEY (event_id, user_id)
);

-- changeset Rooted:1695483434053-5
ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

-- changeset Rooted:1695483434053-6
ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES organizer (organizer_id);

-- changeset Rooted:1695483434053-7
ALTER TABLE user_events
    ADD CONSTRAINT fk_useeve_on_event FOREIGN KEY (event_id) REFERENCES event (event_id);

-- changeset Rooted:1695483434053-8
ALTER TABLE user_events
    ADD CONSTRAINT fk_useeve_on_user FOREIGN KEY (user_id) REFERENCES "user" (user_id);

