name: Dev CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image-tags: ${{ steps.prepare.outputs.image-tags }}
      # Example: image-tags=1-abc123,dev,latest
      relevant-sha: ${{ steps.prepare.outputs.relevant-sha }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Prepare
        id: prepare
        # <CI Build Number>-<Git Commit SHA>
        run: |
          RELEVANT_SHA=${{ github.event.pull_request.head.sha || github.sha }}
          echo "Relevant commit SHA: $RELEVANT_SHA"
          echo "relevant-sha=$RELEVANT_SHA" >> "$GITHUB_OUTPUT"
          
          IMAGE_TAGS=$GITHUB_RUN_NUMBER-$(git rev-parse --short $RELEVANT_SHA)
          echo "image-tags=$IMAGE_TAGS" >> "$GITHUB_OUTPUT"
          echo "Image Tags: $IMAGE_TAGS"

  build-and-push-backend:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    environment: dev
    needs: prepare
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        working-directory: ./backend
        run: |
          gradle jib \
            -Djib.to.tags=${{ needs.prepare.outputs.image-tags }} \
            -Djib.to.auth.username=${{ github.actor }} \
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        component: [ database, frontend, reverse-proxy ]
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare Full Image Names
        id: prepare
        run: |
          COMPONENT_IMAGE="ghcr.io/modhanami/arsahub/${{ matrix.component }}"
          echo "image-names=$(echo ${{ needs.prepare.outputs.image-tags }} | sed "s|\([^,]\+\)|$COMPONENT_IMAGE:\1|g")" >> "$GITHUB_OUTPUT"
      # A step for frontend (only) to generate a .env file using vars from GitHub Context
      - name: Generate .env file
        if: matrix.component == 'frontend'
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}" >> frontend/.env
          echo "NEXT_PUBLIC_SOCKET_IO_URL=${{ vars.NEXT_PUBLIC_SOCKET_IO_URL }}" >> frontend/.env
          echo "NEXT_PUBLIC_IMAGE_BASE_URL=${{ vars.NEXT_PUBLIC_IMAGE_BASE_URL }}" >> frontend/.env
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ vars.NEXT_PUBLIC_SUPABASE_URL }}" >> frontend/.env
          echo "NEXT_PUBLIC_SUPABASE_KEY=${{ vars.NEXT_PUBLIC_SUPABASE_KEY }}" >> frontend/.env
          cat frontend/.env
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.component }}
          push: true
          tags: ${{ steps.prepare.outputs.image-names }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
